# Generated by Django 5.1.3 on 2024-11-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profile_photo",
                    models.FilePathField(
                        default="https://www.google.com/imgres?q=profile%20photo%20icon&imgurl=https%3A%2F%2Fstatic.thenounproject.com%2Fpng%2F3278830-200.png&imgrefurl=https%3A%2F%2Fthenounproject.com%2Fbrowse%2Ficons%2Fterm%2Fprofile-picture%2F&docid=NEcOy5sl1J50NM&tbnid=C4AKfq8OxrJpQM&vet=12ahUKEwj8vMTd692JAxWaIDQIHT9ZJdUQM3oECCIQAA..i&w=200&h=200&hcb=2&ved=2ahUKEwj8vMTd692JAxWaIDQIHT9ZJdUQM3oECCIQAA",
                        max_length=1000,
                    ),
                ),
                ("user", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=1000)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pomapp.post"
                    ),
                ),
            ],
        ),
    ]
