# Generated by Django 5.1.3 on 2024-11-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pomapp", "0002_alter_post_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="id",
        ),
        migrations.AlterField(
            model_name="postimage",
            name="post_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="pomapp.post",
            ),
        ),
    ]
