# Generated by Django 5.1.3 on 2024-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pomapp", "0003_remove_postimage_id_alter_postimage_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="profile_photo",
            field=models.CharField(max_length=4000),
        ),
    ]
